import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    // absolute: "",
    default: "Next.js Tutorial - Arshad Siddiqui",
    template: "%s | Arshad Siddiqui",
  },

  // title: "Create Next App",
  description: "Generated by create next app",
  keywords: ['Next.js', 'React', 'JavaScript', 'mascreation', 'Arshad Siddiqui'],
  authors: [
    { name: 'Arshad Siddiqui', url: 'https://mascreation.tech' }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        {/* Header */}
        <Header></Header>

        {/* Main   */}
        <main>
          {children}
        </main>

        {/* Footer */}
        <Footer></Footer>
      </body>
    </html>
  );
}
